// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Models, Routers, Templates, Views;
    Routers = require("./routers");
    Models = require("./models");
    Views = require("./views");
    Templates = require("./templates");
    return {
      init: function() {
        return new Routers.Test();
      },
      Models: Models,
      Views: Views,
      Templates: Templates
    };
  });

  /*
  define(function (require) {
      var Routers = require('./routers');
          Models = require('./models'),
          Views = require('./views');
          Templates = require('./templates');
  
      return {
          init: function () {
              new Routers.Test();
          },
          Models: Models,
          Views: Views,
          Templates: Templates
      };
  });
  */


}).call(this);
