// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, Modernizr, NextArrow, ResizeFu, em, exports, gVars, makeItHappen, makeNavClick, moduleName, _window;
    $ = require("jquery");
    Modernizr = require("Modernizr");
    NextArrow = require("next_arrow");
    ResizeFu = require("resize_fu");
    NextArrow = require("next_arrow");
    exports = {};
    gVars = {
      scrollSpeed: 0.4,
      logFactor: 1.8
    };
    moduleName = "head_more";
    em = parseInt($("body").css("font-size"), 10);
    _window = $(window);
    makeNavClick = function(_this) {
      return _this.on("click", "li", function(e) {
        var aniSpeed, artOffTop, articleOffset, distance, getID, href, id, voodoo, _links;
        e.preventDefault();
        _links = $(this).find("a");
        if (_links.length === 1) {
          href = _links.attr("href");
          getID = href.split("/");
          window.location.href = href;
          if (getID[1] !== "") {
            id = "#" + getID[1];
            articleOffset = $(id).offset();
            artOffTop = articleOffset.top;
            if ($(id).data("nudge-top") != null) {
              artOffTop += parseInt($(id).data("nudge-top"));
            }
            distance = artOffTop - _window.scrollTop();
            voodoo = Math.log(gVars.logFactor * ($(document).height() / distance));
            if (voodoo < 1) {
              voodoo = 1;
            }
            aniSpeed = Math.round(distance * voodoo / (1 / gVars.scrollSpeed));
            return $("html,body").animate({
              scrollTop: artOffTop
            }, aniSpeed);
          }
        }
      });
    };
    makeItHappen = function(_this) {
      ResizeFu.init(_this);
      makeNavClick(_this.find("nav"));
      return NextArrow.init(_this);
    };
    exports.init = function(_this) {
      var element;
      if (_this !== void 0) {
        return makeItHappen(_this);
      } else {
        element = $("body").find("[data-module=\"" + moduleName + "\"]");
        return element.each(function() {
          return makeItHappen($(this));
        });
      }
    };
    return exports;
  });

}).call(this);
