// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var $, Modernizr, em, exports, gVars, makeItHappen, moduleName, positionMe, _window;
    $ = require("jquery");
    Modernizr = require("Modernizr");
    exports = {};
    moduleName = "take_me";
    _window = $(window);
    em = parseInt($("body").css("font-size"), 10);
    gVars = {
      startEle: {},
      endEle: {},
      navHt: 0
    };
    positionMe = function($this) {
      var scroll, startOff, startOffset, thisTop, windowHt;
      windowHt = _window.height();
      scroll = _window.scrollTop();
      startOffset = gVars.startEle.offset();
      startOff = startOffset.top;
      console.log(startOff, scroll);
      if (scroll <= startOff) {
        thisTop = startOff + windowHt - gVars.navHt;
      } else {
        thisTop = startOff + windowHt - gVars.navHt;
      }
      return $this.css({
        "top": thisTop
      });
    };
    makeItHappen = function(_this) {
      console.log("made it happen for " + moduleName);
      gVars.startEle = _this.next();
      gVars.endEle = _this.siblings().last();
      gVars.navHt = _this.height();
      positionMe(_this);
      _window.scroll(function() {
        return positionMe(_this);
      });
      return _window.resize(function() {
        return positionMe(_this);
      });
    };
    exports.init = function(_this) {
      var element;
      if (_this !== void 0) {
        return makeItHappen(_this);
      } else {
        element = $("body").find("[data-module=\"" + moduleName + "\"]");
        return element.each(function() {
          return makeItHappen($(this));
        });
      }
    };
    return exports;
  });

}).call(this);
